spring:
  application:
    name: TicketSystem


  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_ticket
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 7070
ticketsystem:
  app:
    jwtSecret: ===================jhsajkdjdsjfdsfsdgsgsdfjkdfs===============
    jwtExpirationMs: 86500000


