spring:
  application:
    name: TicketSystem


  datasource:
    username: postgres
    password: "iadp$110"
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_ticket
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 3250
  debug: true
ticketsystem:
  app:
    jwtSecret: ===================jhsajkdjdsjfdsfsdgsgsdfjkdfs===============
    jwtExpirationMs: 86500000


